# patterns are matched in order. the first match will always be used
# therefore, more specific definitions must be higher than general definitions
# patterns are regex and will match path, then route, then module
# any block positions in the template must be defined here
# do not duplicate realm names or later entries will override previous entries
pagesdisplay:
  pattern: zikulapagesmodule_user_display # routeid pattern
  page: ":pagesdisplay.html.twig"
pages:
  pattern: ^/pages # carat indicates path matches only paths *beginning with* `/pages`
  page: ":pages.html.twig"
  block:
    positions:
      left: "Block:block.html.twig"
spec:
  pattern: ZikulaSpecModule # modulename pattern (case insensitive)
  page: ":spec.html.twig"
  block:
    positions:
      left: "Block:block.html.twig"
##
# 'alias' realms ('admin', 'home', and 'master') do not require a pattern and override all other realms
##
admin: # defining an admin realm will be used when @Theme('admin') annotation is detected in the method (even w/o pattern)
  page: ":admin.html.twig"
home: # defining a home realm will be used when the Front Controller is used (e.g. the path is essentially `/`)
  page: ":home.html.twig"
  block:
    positions:
      left: "Block:block.html.twig"
      center: "Block:block.html.twig"
    types:
    instances:
master: # the master realm is required
  page: ":master.html.twig"
  block:
    positions:
      left: "Block:block.html.twig"
    types:
    instances: